exec-once = systemctl --user start hyprpolkitagent
exec-once = swaync
exec-once = wayvar

# Use 100% display scaling on all monitors.
monitor = , preferred, auto, 0.7

general {
    gaps_in = 0
    gaps_out = 0
}
